### PR TITLE
fix #12 issue

### LINKED ISSUE #12: Program exit unexpectedly when clicking snapshot(2D&3D) if display window has nothing
Add message box to remain user to open pcd or camera.

### PR DESCRIPTION
**Pull request by Fibird**
* check if cloud is empty before taking snapshot
* pop message box when cloud or vlcvideo is empty
* add message box to output other errors or infos

### CODE REVIEW

File: ifm3dviewer.cpp [hunk 1]
```diff
@@ -117,14 +119,22 @@ void IFM3DViewer::run()
...
+        QMessageBox::warning(nullptr, tr("Warning"), tr("There are nothing to be taken! Please open a pcd or camera."));
+        return;
+    }
+
     pcl::PointCloud<pcl::PointXYZI> *temp = cloud.get();
+
     // Generate image name according to current time
     QDateTime current_date_time = QDateTime::currentDateTime();
     QString current_date = current_date_time.toString("yyyy-MM-dd-hhmmsszzz");
     QString ssname = qApp->applicationDirPath() + "/" + current_date + ".pcd";
```
Comment (chenyangcheung) [inline ifm3dviewer.cpp:133]: You're so cute, Mr. Liu

**Review by chenyangcheung — COMMENTED** [review]
It's perfect.
